
###############################################################################
#
# Inclusive Makefile for the x86_64_netberg_aurora_610 module.
#
# Autogenerated 2019-10-23 01:41:02.133243
#
###############################################################################
x86_64_netberg_aurora_610_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_netberg_aurora_610_BASEDIR)module/make.mk
include $(x86_64_netberg_aurora_610_BASEDIR)module/auto/make.mk
include $(x86_64_netberg_aurora_610_BASEDIR)module/src/make.mk

